### ISSUE TITLE
Add new location

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/GeoWebServices#13]
Most of the parts for this already exist. 
- We just need to add support for a hit test on the map and then send the x/y to the existing API endpoint to return and present the stack. 
- User could then name the location and it would be added in to a “red cross locations” table of x/y places and a GUID would be created.
- When a place is created the GIS team could then research it and add the place to OSM if appropriate.

**Comment by hallahan** [comment]
I'm closing this issue, because the "placesearch" feature is now part of GeoForce, and the code in this repo is no longer being used.

https://github.com/AmericanRedCross/GeoForce/issues/318
